use dicom_lib::constants::{
    sop_class_uids::{
        COMPUTED_RADIOGRAPHY_IMAGE_STORAGE, CT_IMAGE_STORAGE,
        DIGITAL_MAMMOGRAPHY_X_RAY_IMAGE_STORAGE_FOR_PRESENTATION,
        DIGITAL_X_RAY_IMAGE_STORAGE_FOR_PRESENTATION, MR_IMAGE_STORAGE,
        SECONDARY_CAPTURE_IMAGE_STORAGE, VERIFICATION, X_RAY_ANGIOGRAPHIC_IMAGE_STORAGE,
        X_RAY_RADIOFLUOROSCOPIC_IMAGE_STORAGE,
    },
    transfer_syntax_uids::{EXPLICIT_VR_LITTLE_ENDIAN, IMPLICIT_VR_LITTLE_ENDIAN},
};

// <root>.<app>.<type>.<version>
// root: 1.3.6.1.4.1.64183 (https://www.iana.org/assignments/enterprise-numbers/)
// app: 1 (Oceanus)
// type: 1 (DICOM Server)
// version: x (major version)
pub const IMPLEMENTATION_CLASS_UID: &str =
    concat!("1.3.6.1.4.1.64183.1.1.", env!("CARGO_PKG_VERSION_MAJOR"));
pub const IMPLEMENTATION_VERSION_NAME: &str = concat!("OCEANUS_", env!("CARGO_PKG_VERSION")); // OCEANUS_x.y.z

pub const MAXIMUM_LENGTH: u32 = 0; // 制限なし

pub const SUPPORTED_ABSTRACT_SYNTAX_UIDS: &[&str] = &[
    // C-ECHO
    VERIFICATION,
    // C-STORE
    COMPUTED_RADIOGRAPHY_IMAGE_STORAGE,
    DIGITAL_X_RAY_IMAGE_STORAGE_FOR_PRESENTATION,
    DIGITAL_MAMMOGRAPHY_X_RAY_IMAGE_STORAGE_FOR_PRESENTATION,
    CT_IMAGE_STORAGE,
    MR_IMAGE_STORAGE,
    SECONDARY_CAPTURE_IMAGE_STORAGE,
    X_RAY_ANGIOGRAPHIC_IMAGE_STORAGE,
    X_RAY_RADIOFLUOROSCOPIC_IMAGE_STORAGE,
];
pub const SUPPORTED_TRANSFER_SYNTAX_UIDS: &[&str] = // NOTE: 順序は優先度順
    &[EXPLICIT_VR_LITTLE_ENDIAN, IMPLICIT_VR_LITTLE_ENDIAN];

pub const EXPLICIT_VR_BIG_ENDIAN: &str = "1.2.840.10008.1.2.2";
